### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by amnona**

### CODE REVIEW

**Comment by jwdebelius** [comment]
On `bloom-filtering-main.ipynb`:
- Please rename `GetAGFreshMin` and `GetStorageMax` using snake_case to match with naming conventions for python functions.

**Comment by jwdebelius** [comment]
@mortonjt, maybe you can help.

I installed heatseaker according to the current version on github. I've gotten the following heatseaker related errors... 

When I install according to the instructions, I get a runtime error when this cell is executed:

``` python
plt.figure()
ax = plt.axes()
sn.kdeplot(np.log2(np.array(allx)),np.log2(np.array(ally)),shade=True, cmap='Greys', ax=ax)
plt.scatter(np.log2(np.array(intx)), np.log2(np.array(inty)), s=80, color=sn.color_palette()[2])
ax.set_xlim([-2, 10])
ax.set_ylim([-5, 6])
ax.set_xlabel('max. storage study foldchange (log2)',fontsize=16)
ax.set_ylabel('min. AG foldchange (log2)',fontsize=16)
ax.tick_params(axis='both', which='major', labelsize=14)
plt.tight_layout()
```

This block:

``` python
# remove the AG mapping fields (to make it faster)
hs.filtermapfields(allf,['origexp'],inplace=True)
```

is giving me the following error:

```
# remove the AG mapping fields (to make it faster)
hs.filtermapfields(allf,['origexp'],inplace=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-04fef9afa2d1> in <module>()
      1 # remove the AG mapping fields (to make it faster)
----> 2 hs.filtermapfields(allf,['origexp'],inplace=True)

AttributeError: module 'heatsequer' has no attribute 'filtermapfields'
```

I'm also getting an error here:

``` python
# give nices names to the experiment (for the plot)
hs.addfield(allfpre,'expname',['AG-pre','EWF-pre','PGP-pre','UKTwins-pre'])
```

```
AttributeError                            Traceback (most recent call last)
<ipython-input-49-d0af2d9dd974> in <module>()
      1 # give nices names to the experiment (for the plot)
----> 2 hs.addfield(allfpre,'expname',['AG-pre','EWF-pre','PGP-pre','UKTwins-pre'])

AttributeError: module 'heatsequer' has no attribute 'addfield'
```

And here:

``` python
# plot the taxonomy bar graph (normalized to 100% per study)
taxlist=hs.plottaxonomybar(allfpre,sortfield='expname',showlegend=False,showxlabels=True,rotation=0,sumone=True)
plt.ylabel('Fraction of reads')
plt.tight_layout()
plt.gca().set_xlim([-0.2, 4.0])
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-53-a66de2bf6e94> in <module>()
      1 # plot the taxonomy bar graph (normalized to 100% per study)
----> 2 taxlist=hs.plottaxonomybar(allfpre,sortfield='expname',showlegend=False,showxlabels=True,rotation=0,sumone=True)
      3 plt.ylabel('Fraction of reads')
      4 plt.tight_layout()
      5 plt.gca().set_xlim([-0.2, 4.0])

TypeError: plottaxonomybar() got an unexpected keyword argument 'showxlabels'
```

**Comment by amnona** [comment]
fixed function names as @jwdebelius comment

**Comment by amnona** [comment]
@jwdebelius 
commited latest heatsequer changes. should now work
note that the new version requires qt5 instead of qt4 so need to update qt and pyqt in the conda env (installation instructions have been updated in the readme)

**Comment by wasade** [comment]
Please check off the boxes as these are addressed, or edit this comment message and add a comment inline. Was only able to make it partially through.

In `ag_alpha_diversity.ipynb`:
- [ ] do the figures need to be regenerated to reflect what will be in the manuscript?

amnon: what do you mean?

In `bloom-filtering-main.ipynb`:
- [ ] can messages like "supercooldb loaded" be suppressed please? it will rightfully invite questions surrounding what it is and why its used. If it cannot easily be suppressed, can a note at the top of the notebook be added indicating the messages can be disregarded and are in regards to aspects of heatsequer which are not used here (...assuming that is accurate...)?
- [ ] can the messages indicating the number of bacteria be revised to indicate number of organisms? as is right now, it implies that archaea are implicitly filtered. 
- [ ] in "Song fecal stability study", were only the human data used or were the dog samples used as well?
- [ ] in "PGP", I am perplexed by the message "('Table sample Fermanagh.Mouth not found in mapping file',)" as I _am_ able to find this sample in both the PGP mapping file and PGP gg 97% BIOM table (see [here]) with > 16k reads.
- [ ] please revise the header "Calculate growth for bacteria in storage studies" as this is not specific to bacteria

**Comment by jwdebelius** [comment]
closed in favor of #8

**Pull request closed without merging**
